### ISSUE TITLE
Open Discussion: change library name

### ISSUE THREAD

**Issue by c0nsol3** [ArkEcosystem/python-crypto#124]
**Expected Behavior**

As the ecosystem grows and more projects fork Ark's code they usually also fork `python-crypto` and `python-client` libs. This means developers working in the ecosystem install multiple versions of these same libraries but for different Ark forks.

For example I'd install crypto lib for Ark and Noah (an imaginative fork), like so:
- `pip install arkecosystem-crypto`
- `pip install noah-crypto`

Now I should be able to use both crypto libs in my projects at once, like so:

```py
import ark_crypto
import noah_crypto
```

**Current Behavior**

Currently when I install crypto lib for Ark and Noah (an imaginative fork) I use the following commands
- `pip install arkecosystem-crypto`
- `pip install noah-crypto`

```py
import crypto  # which crypto - Ark's or Noah's?
````

All good till this point. But problem occurs when I try to use both libraries in my project as both projects use the name `crypto` to get imported. This is an issue as it basically means one can not use Python libraries from Ark's ecosystem as they all end up having conflicting names. Given how generic name `crypto` is, it's very likely that another library (not related to Ark) can be using that name which will cause the same issue.

**Possible Solution**

a) Rename `crypto` directory to `ark_crypto` or `arkcrypto`
b) Change the name when packaging the library w/o the need to modify existing directories in the project (I'm not entirely certain this works and it's more difficult to test because you need to publish the library and install it to see if it worked.)

I've only opened this issue in `python-crypto` but it also affects `python-client` and perhaps libraries for other languages as well (depending on how they resolve such name conflicts).

**Comment by faustbrian** [comment]
Did python recently remove import aliasing like `import crypto as ark` or why is that no an option?

**Comment by c0nsol3** [comment]
Still has aliasing, but the issue is which `crypto` are you importing and then aliasing if you have multiple `crypto` libs installed. I've update the possible solution section with two suggestions.

**Comment by faustbrian** [comment]
If you want to you can prepare a PR to rename it to `arkecosystem-crypto` and I'll take a look at it when I get a chance.

**Comment by c0nsol3** [comment]
Alright. I'll play with solution B first to see if we can make it work without changing the directory name to `arkecosystem_crypto` (hyphens aren't allowed when importing in Python, eg: `from arkecosystem-crypto ...`)
