### ISSUE TITLE
Add documentation for running tests

### ISSUE THREAD

**Issue by ciband** [ArkEcosystem/python-crypto#52]
**Is your feature request related to a problem? Please describe.**
I am unsure of how to run python-crypto's unit tests .

**Describe the solution you'd like**
As a new python developer, I would like more documentation on how to setup my development environment to run python-crypto's linter and tests.

**Describe alternatives you've considered**
I have attempted to duplication the steps in the travis.yml file but am unsure what to do with the test.py command.

**Additional context**
I am doing development on Windows.

**Comment by roks0n** [comment]
You can:
- run tests using `make test`
- run linter using: `make lint`

@faustbrian where should we put docs regarding such things? Into `readme.md` or the Ark docs website?

**Comment by ciband** [comment]
Windows users typically don't have access to make without running something like cygwin/WSL/mingw/etc..

Would we want to either transition to something more cross platform (CMake?) or add some additional build option to support the Windows users?

**Comment by roks0n** [comment]
Out of curiosity, do these two commands work on Win:
- run tests: `py.test -v -s`
- run linter: `flake8 .`

**Comment by ciband** [comment]
@roks0n I tired to do some more digging and education.  flake8 runs and produces no output for me (clean run?).  py.test doesn't work and gives an error about not knowing what py.test is.  

Is this the same as pytest -v -s?  The Internet suggested running as either 'pytest' or 'python -m pytest' stating that py.test was the old way to do it.  I'm a python n00b so I don't know the correct answer.  I haven't had a chance to run the other commands but I suspect they will work.  I've ran pytest before.

**Comment by roks0n** [comment]
I'm really not aware how things are supposed to work for Windows, I haven't used one in years. Running `py.test` or `pytest` for me on a Mac produces the same results. Could be that you need to run `pytest` on Windows?

flake8 not giving you any output on a clean branch is good, it means there are no lint errors. It will only show output when there are errors.

**Comment by ciband** [comment]
I think that is the issue.  I just need to run pytest.  The py.test syntax threw me.  I think I have a workaround to the makefile which was my main concern.

If any documentation changes are made you could just instruction windows users to run those commands directly instead of running through make.

Thanks for the help and feel free to close the issue.

**Comment by roks0n** [comment]
I agree we should change `py.test` into `pytest`, given `pytest` actually seems to work on all OS.

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/python-crypto/commit/112bfe2f7f581d317d6be65c0c38dad5c9689f5c
